markdown: rdiscount
pygments: false
permalink: /blog/:title
exclude: ['.rvmrc']
name: 'RubyConf Uruguay'
production_url: 'rubyconfuruguay.org'
google_analytics_id: 'UA-17597818-1'
author:
  name: 'Voluntarios de rubysur y neo'
  email: 'info@rubyconfuruguay.org'
